spring:
  security:
    oauth2:
      client:
        registration:
          my-oidc:
            client-id: XXX.apps.googleusercontent.com
            client-secret: XXX
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8083/login/oauth2/code/redirecturi"
            scope: openid, profile
        provider:
          my-oidc:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
