spring:
  security:
    oauth2:
      client:
        registration:
          my-oidc:
            client-id: xxx
            client-secret: xxx
            authorization-grant-type: authorization_code
            redirect-uri: "https://localhost:8083/login/oauth2/code"
            scope: openid, profile
        provider:
          my-oidc:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
