spring:
  security:
    oauth2:
      client:
        registration:
          my-oidc:
            client-id: 742199856496-4pjvrdf43ab3sjg3s06tobig4nteqtln.apps.googleusercontent.com
            client-secret: d1tl-mxBz61CrRH0UhYw6bm_
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8083/login/oauth2/code/redirecturi"
            scope: openid, profile
        provider:
          my-oidc:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
